#    error.py    #
# Written By GQX #

class InvalidCommandError(Exception): ...

class InvalidAPIOperationError(Exception): ...

class TaskScheduleError(Exception): ...

class ShellCommandError(Exception): ...

class InvalidButtonError(Exception): ...